### ISSUE TITLE
Can't find variable: shake

### ISSUE THREAD

**Issue by jorisw** [leecrossley/cordova-plugin-shake#18]
Hi,

I'm using PhoneGap (Cordova 5.0.0) with Ionic 1.0.0, a mobile development framework based on Angular.

Your docs say a 'shake' object is added to the root. However, as soon as I try to read that object my JS bugs out saying:

`Can't find variable: shake`

I have added your plugin though `cordova plugin add cordova-plugin-shake` and rebuilt my project.

This is my full plug-in list:

```
com.ionic.keyboard 1.0.4 "Keyboard"
com.phonegap.plugins.PushPlugin 2.4.0 "PushPlugin"
cordova-plugin-shake 0.5.1 "Shake Gesture Detection"
org.apache.cordova.console 0.2.13 "Console"
org.apache.cordova.device 0.3.0 "Device"
org.apache.cordova.device-motion 0.2.11 "Device Motion"
```

FWIW, one warning npm gave me when installing your plug-in was:
```
WARNING: org.apache.cordova.device-motion has been renamed to cordova-plugin-device-motion. You may not be getting the latest version! We suggest you `cordova plugin rm org.apache.cordova.device-motion` and `cordova plugin add cordova-plugin-device-motion`.
```

**Comment by leecrossley** [comment]
Please create a sample app that reproduces the issue and push to Github

**Comment by jorisw** [comment]
Found and resolved the problem, which is outside of your script but probably relevant to others using PhoneGap / Cordova with Angular:

Cordova usually finishes loading after AngularJS initiates, causing plug-ins such as shake, that create global objects, to become available a tiny bit too late for immediate access.

The solution is to instantiate Angular after the document.deviceready event. See http://stackoverflow.com/questions/21556090/cordova-angularjs-device-ready for various ways to do this.
