### ISSUE TITLE
Doesn't work in iOs simulator

### ISSUE THREAD

**Issue by lpender** [leecrossley/cordova-plugin-shake#26]
Coffescript:

```coffee
Meteor.startup ->
  if Meteor.isCordova
    alert('here')
    shake.startWatch( ->
      alert('shake')
    )
```

In the simulator I see "here" and simulate a shake gesture and but never see "shake".

Thanks!

**Comment by leecrossley** [comment]
yep, it only works on real devices this one. If you *need* simulator support, it could be possible but would be a simulation...

**Comment by Ritzlgrmft** [comment]
Solved by https://github.com/leecrossley/cordova-plugin-shake/commit/e13c6e7a06c7b5d035d1cbf69ab08ee60778b2d2

**Comment by Ritzlgrmft** [comment]
Now the new version needs to be published...
@leecrossley: will you do it (after increasing the version)?

**Comment by leecrossley** [comment]
v0.6.0 published
