### ISSUE TITLE
Error:"git" command line tool is not installed

### ISSUE THREAD

**Issue by WongGithub** [leecrossley/cordova-plugin-shake#3]
hi, leecorssley! thanks for your plugin.

but i installed it is error, errorinfo:" Error:"git" command line tool is not installed: make sure it is accessible on your PATH"...

**Comment by Marinofull** [comment]
In my case, the git was installed, and git clone works, so:
[this worked in my case](https://stackoverflow.com/questions/17778032/manually-install-device-plugin-and-others-into-cordova-3-0/25314991#25314991)
