### ISSUE TITLE
Support for Cordova 9

### ISSUE THREAD

**Issue by r-guerin** [leecrossley/cordova-plugin-shake#34]
Hi,

As you can see there https://github.com/arnesson/cordova-plugin-firebase/issues/1033 Cordova 9 deprecate the use of requireCordovaModule for non Cordova modules.

Would it be possible to make those changes please ?

**Comment by remisture** [comment]
I need this as well

**Comment by ludufre** [comment]
Me too

**Comment by ludufre** [comment]
I fixed and submitted PR #35

**Comment by Ritzlgrmft** [comment]
I merged the PR, thanks for it, @ludufre.
@leecrossley: could you please publish a new version to npm?  

In the meanwhile, you can add the plugin directly from https://github.com/leecrossley/cordova-plugin-shake.git.

**Comment by remisture** [comment]
Could someone please publish the latest version to `npm`?

**Comment by ChrisTomAlx** [comment]
Pretty please :)

**Comment by FanYeeChok** [comment]
waiting

**Comment by ludufre** [comment]
I fixed this problem on April 25th. And until today it was not published on npm. I think they abandon this project completely ...

**Comment by ChrisTomAlx** [comment]
I ended up forking and creating my own plugin on npm.. Really did not want to .. But no other option..
If it will help anyone else stumbling upon this.. Here you go.. 
https://www.npmjs.com/package/cordova-plugin-neushake

**Comment by FanYeeChok** [comment]
> I ended up forking and creating my own plugin on npm.. Really did not want to .. But no other option..
> If it will help anyone else stumbling upon this.. Here you go..
> https://www.npmjs.com/package/cordova-plugin-neushake

No choice. Thanks anyway. Will it cause @ionic-native/shake unable to use if using your cordova-plugin-neushake ?

**Comment by leecrossley** [comment]
Published, apologies - https://www.npmjs.com/package/cordova-plugin-shake
