### ISSUE TITLE
iOS shake detection doesn't work

### ISSUE THREAD

**Issue by idoodler** [leecrossley/cordova-plugin-shake#37]
We recently updated to the latest cordova for iOS 6.2.0.

This plugin injects the `motionEnded` function in to the `MainViewController.m` file but it looks like nothing from the `MainViewController.m`file is called.

Does someone experience the same behaviour?

**Comment by Ritzlgrmft** [comment]
Maybe this helps, at least to understand your issue better: https://github.com/leecrossley/cordova-plugin-shake/issues/36#issuecomment-647161870

**Comment by idoodler** [comment]
We are using plain cordova, not capacitor. It looks like the MainViewController.m file is deprecated and not used anymore. If i manually add the `motionEnded` method function to `CDVViewController.h` inside the CordovaLib project it works fine.
